
slidify::slidify('lectures/lecture01_intro2data_science_and_R.Rmd')
slidify::slidify('lectures/Lecture02_r_basics.Rmd')
slidify::slidify('lectures/lecture03_data_structures.Rmd')
slidify::slidify('lectures/lecture04_operators.Rmd')
slidify::slidify('lectures/lecture05_data_wrangling_import.Rmd')
slidify::slidify('lectures/lecture06_data_wrangling_tidy_data.Rmd')
slidify::slidify('lectures/lecture07_data_wrangling_transformation.Rmd')
slidify::slidify('lectures/lecture08_intro2visualization_1.Rmd')
slidify::slidify('lectures/lecture09_intro2visualization_2.Rmd')
slidify::slidify('lectures/lecture10_categorical_data.Rmd')
slidify::slidify('lectures/lecture11_rmarkdown.Rmd')
slidify::slidify('lectures/lecture12_stat_modelling_1.Rmd')
slidify::slidify('lectures/lecture13_stat_modelling_2.Rmd')
slidify::slidify('lectures/lecture14_stat_modelling_3.Rmd')
slidify::slidify('lectures/lecture15_stat_modelling_4.Rmd')
slidify::slidify('lectures/lecture16_string_manipulation.Rmd')
slidify::slidify('lectures/lecture17_functionsniterations_1.Rmd')
slidify::slidify('lectures/lecture18_iterations_2.Rmd')

